// <auto-generated>
// 斗兽奇弈：技能形状表 + 通用组件。
// 形状来自 XBM 技能详情表（CastType/EffectRange/XAxisModifier/Omen）；
// 实录组通过通用或专用组件使用 spell.LocXZ；未录制组默认施法者，TargetArea=True 用落点；
// 全体/大范围（不可躲避）、击退、友方目标不进入 AOE 表，改为提示。
// </auto-generated>
namespace BossMod.Dawntrail.Foray.Crucible;

using BossMod.Dawntrail.Foray.CriticalEngagement;

// 一条可绘制技能的配置
public readonly record struct CrucibleSpell(AOEShape Shape, bool LocationTargeted = false);

static class CrucibleSpells
{
    // ActionID -> 形状配置
    public static readonly Dictionary<uint, CrucibleSpell> Table = new()
    {
        [46866] = new(new AOEShapeCircle(6f)),  // 古墓 | 奇子·骑士 [14531]
        [46868] = new(new AOEShapeDonut(4f, 40f)),  // 死亡螺旋 | 奇子·主教 [14532]
        [46870] = new(new AOEShapeRect(40f, 4f)),  // 古代疾风 | 奇子·主教 [14532]
        [46874] = new(new AOEShapeCircle(5f), LocationTargeted: true),  // 黑火喷发 | 奇子·主教
        [46876] = new(new AOEShapeRect(40f, 2f)),  // 深渊飞刺 | 深渊之枪 [14534] | 手工补充（ARR 实测）
        [46879] = new(new AOEShapeRect(35f, 4f)),  // 肢解 | 奇子·上级恶魔
        [46882] = new(new AOEShapeCircle(6f)),  // 深渊贯穿 | 奇子·上级恶魔
        [46884] = new(new AOEShapeCircle(3f)),  // 深渊贯穿 | 奇子·上级恶魔
        [46886] = new(new AOEShapeCone(40f, 90f.Degrees())),  // 深渊回转 | 奇子·上级恶魔 [14533]
        [46889] = new(new AOEShapeCircle(5f), LocationTargeted: true),  // 虚空冰封 | 奇子·夺灵魔 [14535] | 手工补充（ARR 实测）
        [46892] = new(new AOEShapeCross(50f, 5f)),  // 虚空暴雷 | 奇子·夺灵魔 [14535]
        [46897] = new(new AOEShapeDonut(5f, 60f), LocationTargeted: true),  // 虚空暴风 | 奇子·夺灵魔 [14535] | 手工补充（ARR 实测）
        [46900] = new(new AOEShapeCircle(5f), LocationTargeted: true),  // 黑火喷发 | 奇子·主教
        [46902] = new(new AOEShapeCircle(6f)),  // 地面隆起 | 奇子·祸蛛蝎
        [46903] = new(new AOEShapeDonut(6f, 12f)),  // 地面隆起 | 奇子·祸蛛蝎
        [46904] = new(new AOEShapeDonut(12f, 18f)),  // 地面隆起 | 奇子·祸蛛蝎
        [46905] = new(new AOEShapeDonut(18f, 24f)),  // 地面隆起 | 奇子·祸蛛蝎
        [46908] = new(new AOEShapeCircle(9f), LocationTargeted: true),  // 毒蛛网 | 奇子·祸蛛蝎
        [46909] = new(new AOEShapeRect(40f, 2f)),  // 蛛网屏 | 奇子·灵蛛蝎 [14537]
        [46912] = new(new AOEShapeCone(40f, 60f.Degrees())),  // 燃烧猛击 | 奇子·食人魔 [14538]
        [46916] = new(new AOEShapeCircle(3f), LocationTargeted: true),  // 熔岩 | 奇子·食人魔
        [46917] = new(new AOEShapeCircle(5f), LocationTargeted: true),  // 熔岩 | 奇子·食人魔
        [46924] = new(new AOEShapeDonut(8f, 40f)),  // 血雨 | 魅惑女妖 帕德索 [14541]
        [46926] = new(new AOEShapeCircle(8f)),  // 血雨 | 魅惑女妖 帕德索
        [46929] = new(new AOEShapeCircle(10f), LocationTargeted: true),  // 虚空烈炎 | 奇子·梦魔法师 [14542]
        [46930] = new(new AOEShapeCone(10f, 60f.Degrees())),  // 甜钢 | 奇子·梦魔骑士 [14543]
        [46932] = new(new AOEShapeRect(60f, 4f)),  // 虚空烈风 | 魅惑女妖 帕德索
        [46933] = new(new AOEShapeCone(60f, 10f.Degrees())),  // 虚空烈风 | 魅惑女妖 帕德索
        [48137] = new(new AOEShapeCircle(30f)),  // 重锤跃击 | 奇子·曼提克 [14545]
        [48155] = new(new AOEShapeCircle(8f)),  // 中心破灭 | 奇子·牛头魔 [14546]
        [48157] = new(new AOEShapeDonut(7f, 50f)),  // 外环破灭 | 未找到详情引用 | 内半径来自 Omen 命名，待实测
        [48175] = new(new AOEShapeCone(60f, 90f.Degrees())),  // 炽热弥漫 | 奇子·双足飞龙 [14549]
        [48186] = new(new AOEShapeCircle(18f)),  // 暗天球 | 奇子·虚灵法师 [14552]
        [48218] = new(new AOEShapeRect(40f, 5f)),  // 狂怒一击 | 奇子·恶魔兵装 [14558]
        [48219] = new(new AOEShapeDonut(4f, 30f)),  // 狂怒一击 | 奇子·恶魔兵装 [14558]
        [48223] = new(new AOEShapeCone(12f, 45f.Degrees())),  // 定罪 | 奇子·恶魔 [14557]
        [48227] = new(new AOEShapeCone(60f, 45f.Degrees())),  // 黄沙吐息 | 小地豆 [14562]
        [48229] = new(new AOEShapeCircle(8f)),  // 哥布流回旋剑 | 寻兽探奇 路斯福洛克斯 [14561]
        [48473] = new(new AOEShapeCone(60f, 65f.Degrees())),  // 钢铁裂斩 | 奇子·游侠骑士 [14564]
        [48497] = new(new AOEShapeCone(15f, 90f.Degrees())),  // 前方乱流 | 奇子·祖 [14572]
        [48499] = new(new AOEShapeCone(15f, 90f.Degrees())),  // 后方乱流 | 奇子·祖 [14572]
        [48512] = new(new AOEShapeCone(60f, 90f.Degrees())),  // 邪光 | 奇子·卡托布莱帕斯 [14577]
        [48555] = new(new AOEShapeRect(45f, 5f)),  // 岩石崩溃 | 奇子·巨像 [14581]
        [48556] = new(new AOEShapeRect(45f, 5f)),  // 滑坡 | 奇子·拉哈穆 [14580]
        [48575] = new(new AOEShapeDonut(2.58f, 43f)),  // 亡者之歌 | 奇子·塞壬 [14583]
        [48581] = new(new AOEShapeCircle(15f)),  // ？针刺 | 奇子·士兵 [14590]
        [48588] = new(new AOEShapeDonut(5f, 40f)),  // 乱针刺 | 奇子·勇士 [14587]
        [48620] = new(new AOEShapeRect(50f, 3f)),  // 霹雳 | 贪食无厌 加特勒 [14592]
        [48673] = new(new AOEShapeCone(50f, 45f.Degrees())),  // 恶臭气 | 奇子·魔界花 [14599]
        [48679] = new(new AOEShapeCircle(6f)),  // 酸雾 | 奇子·大口花 [14601]
        [48691] = new(new AOEShapeRect(45f, 6f)),  // 腐烂恶臭 | 奇子·尸生花 [14603]
        [48704] = new(new AOEShapeRect(46f, 11.5f)),  // 低温俯冲 | 奇子·冰龙 [14606]
        [48708] = new(new AOEShapeCircle(9f), LocationTargeted: true),  // 无终的枯朽 | 奇子·冰龙 [14606]
        [48720] = new(new AOEShapeCircle(13f)),  // 圆环连斩 | 奇子·石像鬼 [14608]
        [48727] = new(new AOEShapeRect(60f, 3.5f)),  // 荒芜新星 | 奇子·石像鬼 [14608]
        [48735] = new(new AOEShapeRect(40f, 2.5f)),  // 自动火炮 | 奇子·无人机 [14614]
        [48736] = new(new AOEShapeCircle(5f)),  // 旋转挥打 | 奇子·发条步兵 [14612]
        [48737] = new(new AOEShapeCircle(6f)),  // 魔力爆散 | 未找到详情引用
        [48747] = new(new AOEShapeCone(40f, 60f.Degrees())),  // 火炎放射 | 奇子·管理者 [14610]
        [48757] = new(new AOEShapeCircle(8f)),  // 岩雨 | 奇子·巨像 [14617]
        [48768] = new(new AOEShapeCone(40f, 30f.Degrees())),  // 岩突 | 奇子·巨像 [14617]
        [48781] = new(new AOEShapeCircle(3f)),  // 橡果炸弹 | 奇子·树精 [14618]
        [48783] = new(new AOEShapeCircle(5f)),  // 释放汁液 | 奇子·蛞蝓 [14619]
        [48785] = new(new AOEShapeRect(40f, 2f)),  // 蛛网屏 | 奇子·凶蛛蝎 [14621]
        [48771] = new(new AOEShapeCircle(12f)),  // 巨木龙卷首圈 | 奇子·树精 [14618]
        [48772] = new(new AOEShapeDonut(12f, 18f)),
        [48773] = new(new AOEShapeDonut(18f, 24f)),
        [48774] = new(new AOEShapeDonut(24f, 30f)),
        [48775] = new(new AOEShapeDonut(30f, 36f)),
        [48778] = new(new AOEShapeCone(60f, 45f.Degrees())), // 簌簌轻风 gl_fan090
        [48779] = new(new AOEShapeCone(60f, 75f.Degrees())),
        [48780] = new(new AOEShapeCone(60f, 75f.Degrees())),
        [48791] = new(new AOEShapeCircle(5f), LocationTargeted: true),  // 烈炎 | 奇子·爆弹怪 [14625]
        [48792] = new(new AOEShapeCircle(6f)),  // 自爆 | 奇子·爆弹怪 [14625]
        [48794] = new(new AOEShapeCircle(10f)),  // 冰碎 | 奇子·雪弹怪 [14626]
        [48796] = new(new AOEShapeCone(40f, 10f.Degrees())),  // 剧毒烟雾 | 奇子·焰球 [14627]
        [48801] = new(new AOEShapeRect(40f, 6f)),  // 熔毁 | 奇子·爆弹之母 [14623]
        [48810] = new(new AOEShapeCircle(6f)),  // 猛毒粘液 | 怨毒龙 博尔格尼 [14628]
        [48809] = new(new AOEShapeCircle(6f), LocationTargeted: true), // 猛毒粘液落点
        [48812] = new(new AOEShapeCircle(6f), LocationTargeted: true), // 连续毒圈详情行
        [48814] = new(new AOEShapeRect(48f, 10f)),  // 低温俯冲 | 怨毒龙 博尔格尼 [14628]
        [49193] = new(new AOEShapeRect(50f, 20f)),  // 蓄电雷击 | 奇子·佛劳洛斯 [14631]
        [49194] = new(new AOEShapeRect(100f, 1f)),  // 线状放电 | 雷元精 [14632]
        [49196] = new(new AOEShapeCircle(6f)),  // 飞散 | 奇子·毒性魔菇 [14634]
        [49200] = new(new AOEShapeCircle(8f)),  // 虚空狂水 | 奇子·夺心魔 [14633]
        [49210] = new(new AOEShapeCircle(9f)),  // 爆炸 | 奇子·爆弹怪 [14640]
        [49212] = new(new AOEShapeCone(20f, 22.5f.Degrees())),  // 光散射 | 光元精 [14641]
        [49240] = new(new AOEShapeCone(60f, 60f.Degrees())),  // 昏暗 | 奇子·阿托莫斯 [14642]
        [49243] = new(new AOEShapeCircle(6f)),  // 爆炎 | 奇子·软糊怪 [14645]
        [49246] = new(new AOEShapeCircle(5f)),  // 暴雷 | 奇子·甜羹怪 [14647]
        [49247] = new(new AOEShapeCircle(6f), LocationTargeted: true),  // 恐怖眼 | 奇子·石像魔 [14648]
        [49248] = new(new AOEShapeCone(28f, 60f.Degrees())),  // 腐烂吐息 | 奇子·威胁扎哈克 [14649]
        [49249] = new(new AOEShapeCone(30f, 45f.Degrees())),  // 尾部打击 | 奇子·威胁扎哈克 [14649]
        [49252] = new(new AOEShapeCircle(20f)),  // 乱针刺 | 奇子·棘鼹 [14653]
        [49265] = new(new AOEShapeCircle(20f)),  // 雷气释放 | 奇子·杜尔迦 [14657]
        [49278] = new(new AOEShapeCone(60f, 22.5f.Degrees())),  // 石化光照射 | 奇子·美杜莎 [14660]
        [49284] = new(new AOEShapeCircle(5f), LocationTargeted: true),  // 烈火回环 | 奇子·拉米亚 [14661]
        [49289] = new(new AOEShapeCircle(6f)),  // 圆斩剑前置 | 奇子·美杜莎 [14660]
        [49291] = new(new AOEShapeDonut(5f, 60f)),  // 环斩剑前置 | 奇子·拉米亚 [14661]
        [49293] = new(new AOEShapeDonut(5f, 60f)),  // 环斩剑辅助体 | 奇子·拉米亚 [14661]
        [49295] = new(new AOEShapeCircle(6f)),  // 圆斩剑 | 奇子·美杜莎 [14660]
        [49286] = new(new AOEShapeCircle(6f)),  // 恐惧瘴气 | 奇子·拉米亚 [14661]
        [49296] = new(new AOEShapeCone(60f, 22.5f.Degrees()), LocationTargeted: true),  // 冲击波辅助体 | 8方向45度扇形
        [49297] = new(new AOEShapeCircle(20f)),  // 千吨回转 | 奇子·独眼巨人 [14662]
        [49306] = new(new AOEShapeCircle(12f)),  // 冰结咆哮 | 奇子·奇美拉 [14663]
        [49308] = new(new AOEShapeDonut(8f, 40f)),  // 雷电咆哮 | 奇子·奇美拉 [14663]
        [49315] = new(new AOEShapeCircle(12f)),  // 冰结大咆哮 | 奇子·奇美拉 [14663]
        [49316] = new(new AOEShapeDonut(8f, 40f)),  // 雷电大咆哮 | 奇子·奇美拉 [14663]
        [49320] = new(new AOEShapeCircle(6f), LocationTargeted: true),  // 寒冰眼 | 奇子·奇美拉 [14663]
        [49318] = new(new AOEShapeCircle(6f), LocationTargeted: true),  // 无序的和声 | 奇子·奇美拉 [14663]
        [49300] = new(new AOEShapeCone(60f, 120f.Degrees())),  // 寒冰吐息辅助体 | fan240
        [49302] = new(new AOEShapeCone(60f, 120f.Degrees())),  // 雷鸣吐息辅助体 | fan240
        [49304] = new(new AOEShapeCone(60f, 120f.Degrees())),  // 火焰吐息辅助体 | fan240
        [49327] = new(new AOEShapeCone(60f, 120f.Degrees())),  // 后续寒冰吐息辅助体 | fan240
        [49329] = new(new AOEShapeCone(60f, 120f.Degrees())),  // 后续雷鸣吐息辅助体 | fan240
        [49331] = new(new AOEShapeCone(60f, 120f.Degrees())),  // 后续火焰吐息辅助体 | fan240
        [49332] = new(new AOEShapeCircle(60f)),  // 毒性爆发 | 全场
        [49359] = new(new AOEShapeCircle(15f)),  // 巨躯狂怒 | 奇子·巨人 [14670]
        [49361] = new(new AOEShapeCone(40f, 90f.Degrees()), true),
        [49363] = new(new AOEShapeCone(40f, 90f.Degrees()), true),
        [49366] = new(new AOEShapeCircle(6f), true),
        [49379] = new(new AOEShapeRect(7f, 2f), true),
        [49367] = new(new AOEShapeRect(40f, 1.5f)),  // 怒视 | 奇子·独眼巨人 [14671]
        [49370] = new(new AOEShapeRect(40f, 1.5f)),  // 怒视 | 奇子·独眼巨人 [14662]
        [49378] = new(new AOEShapeRect(40f, 4f)),  // 粉碎重踏 | 奇子·巨人 [14670]
        [49381] = new(new AOEShapeCone(60f, 30f.Degrees())),  // 百库啵横扫 | 奇子·莫古小猛 [14675]
        [49383] = new(new AOEShapeCircle(22f)),  // 莫古暴风雨 | 奇子·莫古小猛 [14675]
        [49408] = new(new AOEShapeCone(30f, 60f.Degrees())),  // 巨剑 | 奇子·铁巨人 [14685]
        [49411] = new(new AOEShapeCross(25f, 2.5f)),  // 十字放雷 | 雷元精 [14686]
        [49415] = new(new AOEShapeCircle(12f)),  // 大漩涡 | 奇子·贝希摩斯 [14684]
        [49470] = new(new AOEShapeRect(50f, 3f)),  // 霹雳 | 魔斧之主 劳妲 [14693]
        [49451] = new(new AOEShapeRect(80f, 10f), true),
        [49464] = new(new AOEShapeRect(60f, 3f), true),
        [49483] = new(new AOEShapeRect(50f, 2.5f), true),
        [50848] = new(new AOEShapeRect(60f, 3f), true),
        [49688] = new(new AOEShapeCone(40f, 60f.Degrees())),  // 燃烧猛击 | 奇子·食人魔
        [49886] = new(new AOEShapeCircle(5f), LocationTargeted: true),  // 虚空冰封 | 奇子·夺灵魔 [14535] | 手工补充（ARR 实测）
        [50662] = new(new AOEShapeRect(5f, 1.5f)),  // 敲击 | 奇子·蹒跚鬼 [14585]
        [50943] = new(new AOEShapeCircle(6f)),  // 绒绒陨石雨 | 奇子·莫古小术 [14679]
    };
}

// 通用 AOE 组件：复用 CriticalEngagement 的重复包/墓碑去重逻辑，按战斗分组过滤。
[SkipLocalsInit]
class CrucibleCastAOEs(BossModule module, Battle battle) : ReplayValidatedCastAOEs(module)
{
    private readonly Battle _battle = battle;

    protected override AOEConfig? ConfigFor(uint actionID)
    {
        if ((_battle == Battle.B04 && (CrucibleGroundUpliftAOEs.IsUplift(actionID) || actionID == 46908))
            || !CrucibleSpells.Table.TryGetValue(actionID, out var spell))
        {
            return null;
        }
        // 只有本组敌人的技能才绘制
        var battles = CrucibleSpellBattles.BattlesFor(actionID);
        // First-board NPC cast packets carry the actual AOE origin, including relocated helpers.
        return battles.Contains(_battle) ? new AOEConfig(spell.Shape, _battle <= Battle.B07 || spell.LocationTargeted) : null;
    }
}

// ActionID -> 所属战斗组（由生成器写入）
static class CrucibleSpellBattles
{
    private static readonly Dictionary<uint, Battle[]> _map = new()
    {
        [46866] = [Battle.B01],
        [46868] = [Battle.B01],
        [46870] = [Battle.B01],
        [46874] = [Battle.B01, Battle.B14],
        [46876] = [Battle.B02],
        [46879] = [Battle.B02],
        [46882] = [Battle.B02],
        [46884] = [Battle.B02],
        [46886] = [Battle.B02],
        [46889] = [Battle.B03],
        [46892] = [Battle.B03],
        [46897] = [Battle.B03],
        [46900] = [Battle.B01, Battle.B14],
        [46902] = [Battle.B04],
        [46903] = [Battle.B04],
        [46904] = [Battle.B04],
        [46905] = [Battle.B04],
        [46908] = [Battle.B04],
        [46909] = [Battle.B04],
        [46912] = [Battle.B05],
        [46916] = [Battle.B05],
        [46917] = [Battle.B05],
        [46924] = [Battle.B06],
        [46926] = [Battle.B06],
        [46929] = [Battle.B06],
        [46930] = [Battle.B06],
        [46932] = [Battle.B06],
        [46933] = [Battle.B06],
        [48137] = [Battle.B07],
        [48155] = [Battle.B08],
        [48157] = [Battle.B08],
        [48175] = [Battle.B09],
        [48186] = [Battle.B10],
        [48218] = [Battle.B12],
        [48219] = [Battle.B12],
        [48223] = [Battle.B12],
        [48227] = [Battle.B13],
        [48229] = [Battle.B13],
        [48473] = [Battle.B14],
        [48497] = [Battle.B16],
        [48499] = [Battle.B16],
        [48512] = [Battle.B17],
        [48555] = [Battle.B18],
        [48556] = [Battle.B18],
        [48575] = [Battle.B19],
        [48581] = [Battle.B20],
        [48588] = [Battle.B20],
        [48620] = [Battle.B21],
        [48673] = [Battle.B23],
        [48679] = [Battle.B23],
        [48691] = [Battle.B24],
        [48704] = [Battle.B25],
        [48708] = [Battle.B25],
        [48720] = [Battle.B26],
        [48727] = [Battle.B26],
        [48735] = [Battle.B27],
        [48736] = [Battle.B27],
        [48737] = [Battle.B27],
        [48747] = [Battle.B27],
        [48757] = [Battle.B28],
        [48768] = [Battle.B28],
        [48781] = [Battle.B29],
        [48783] = [Battle.B29],
        [48785] = [Battle.B29],
        [48771] = [Battle.B29],
        [48772] = [Battle.B29],
        [48773] = [Battle.B29],
        [48774] = [Battle.B29],
        [48775] = [Battle.B29],
        [48778] = [Battle.B29],
        [48779] = [Battle.B29],
        [48780] = [Battle.B29],
        [48791] = [Battle.B30],
        [48792] = [Battle.B30],
        [48794] = [Battle.B30],
        [48796] = [Battle.B30],
        [48801] = [Battle.B30],
        [48810] = [Battle.B31],
        [48809] = [Battle.B31],
        [48812] = [Battle.B31],
        [48814] = [Battle.B31],
        [49193] = [Battle.B32],
        [49194] = [Battle.B32],
        [49196] = [Battle.B33],
        [49200] = [Battle.B33],
        [49210] = [Battle.B34],
        [49212] = [Battle.B34],
        [49240] = [Battle.B35],
        [49243] = [Battle.B35],
        [49246] = [Battle.B35],
        [49247] = [Battle.B35],
        [49248] = [Battle.B35],
        [49249] = [Battle.B35],
        [49252] = [Battle.B36],
        [49265] = [Battle.B37],
        [49278] = [Battle.B38],
        [49284] = [Battle.B38],
        [49289] = [Battle.B38],
        [49291] = [Battle.B38],
        [49293] = [Battle.B38],
        [49295] = [Battle.B38],
        [49286] = [Battle.B38],
        [49296] = [Battle.B38],
        [49297] = [Battle.B38],
        [49306] = [Battle.B39],
        [49308] = [Battle.B39],
        [49315] = [Battle.B39],
        [49316] = [Battle.B39],
        [49320] = [Battle.B39],
        [49318] = [Battle.B39],
        [49300] = [Battle.B39],
        [49302] = [Battle.B39],
        [49304] = [Battle.B39],
        [49327] = [Battle.B39],
        [49329] = [Battle.B39],
        [49331] = [Battle.B39],
        [49332] = [Battle.B39],
        [49359] = [Battle.B41],
        [49361] = [Battle.B41],
        [49363] = [Battle.B41],
        [49366] = [Battle.B41],
        [49379] = [Battle.B41],
        [49367] = [Battle.B41],
        [49370] = [Battle.B38],
        [49378] = [Battle.B41],
        [49381] = [Battle.B42],
        [49383] = [Battle.B42],
        [49408] = [Battle.B43],
        [49411] = [Battle.B43],
        [49415] = [Battle.B43],
        [49470] = [Battle.B45],
        [49451] = [Battle.B45],
        [49464] = [Battle.B45],
        [49483] = [Battle.B45],
        [50848] = [Battle.B45],
        [49688] = [Battle.B05],
        [49886] = [Battle.B03],
        [50662] = [Battle.B19],
        [50943] = [Battle.B42],
    };

    public static ReadOnlySpan<Battle> BattlesFor(uint actionID) => _map.TryGetValue(actionID, out var v) ? v : [];
}

// 每组敌人的 AOE 组件（ActivateOnEnter 需要单参数构造函数）

// 第 1 组（斗兽奇弈 第一盘）
[SkipLocalsInit]
sealed class XBMB01AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B01);

// 第 2 组（斗兽奇弈 第一盘）
[SkipLocalsInit]
sealed class XBMB02AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B02);

// 第 3 组（斗兽奇弈 第一盘）
[SkipLocalsInit]
sealed class XBMB03AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B03);

// 第 4 组（斗兽奇弈 第一盘）
[SkipLocalsInit]
sealed class XBMB04AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B04);

// 第 5 组（斗兽奇弈 第一盘）
[SkipLocalsInit]
sealed class XBMB05AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B05);

// 第 6 组（斗兽奇弈 第一盘）
[SkipLocalsInit]
sealed class XBMB06AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B06);

// 第 7 组（斗兽奇弈 第二盘）
[SkipLocalsInit]
sealed class XBMB07AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B07);

// 第 8 组（斗兽奇弈 第二盘）
[SkipLocalsInit]
sealed class XBMB08AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B08);

// 第 9 组（斗兽奇弈 第二盘）
[SkipLocalsInit]
sealed class XBMB09AOE(BossModule module) : Low2CrucibleCastAOEs(module, Battle.B09);

// 第 10 组（斗兽奇弈 第二盘）
[SkipLocalsInit]
sealed class XBMB10AOE(BossModule module) : Low2CrucibleCastAOEs(module, Battle.B10);

// 第 11 组（斗兽奇弈 第二盘）
[SkipLocalsInit]
sealed class XBMB11AOE(BossModule module) : Low2CrucibleCastAOEs(module, Battle.B11);

// 第 12 组（斗兽奇弈 第二盘）
[SkipLocalsInit]
sealed class XBMB12AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B12);

// 第 13 组（斗兽奇弈 第二盘）
[SkipLocalsInit]
sealed class XBMB13AOE(BossModule module) : Low2CrucibleCastAOEs(module, Battle.B13);

// 第 14 组（斗兽奇弈 第三盘）
[SkipLocalsInit]
sealed class XBMB14AOE(BossModule module) : Low3CrucibleCastAOEs(module, Battle.B14);

// 第 15 组（斗兽奇弈 第三盘）
[SkipLocalsInit]
sealed class XBMB15AOE(BossModule module) : Low3CrucibleCastAOEs(module, Battle.B15);

// 第 16 组（斗兽奇弈 第三盘）
[SkipLocalsInit]
sealed class XBMB16AOE(BossModule module) : Low3CrucibleCastAOEs(module, Battle.B16);

// 第 17 组（斗兽奇弈 第三盘）
[SkipLocalsInit]
sealed class XBMB17AOE(BossModule module) : Low3CrucibleCastAOEs(module, Battle.B17);

// 第 18 组（斗兽奇弈 第三盘）
[SkipLocalsInit]
sealed class XBMB18AOE(BossModule module) : Low3CrucibleCastAOEs(module, Battle.B18);

// 第 19 组（斗兽奇弈 第三盘）
[SkipLocalsInit]
sealed class XBMB19AOE(BossModule module) : Low3CrucibleCastAOEs(module, Battle.B19);

// 第 20 组（斗兽奇弈 第三盘）
[SkipLocalsInit]
sealed class XBMB20AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B20);

// 第 21 组（斗兽奇弈 第三盘）
[SkipLocalsInit]
sealed class XBMB21AOE(BossModule module) : Low3CrucibleCastAOEs(module, Battle.B21);

// 第 22 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB22AOE(BossModule module) : HighCrucibleCastAOEs(module, Battle.B22);

// 第 23 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB23AOE(BossModule module) : HighCrucibleCastAOEs(module, Battle.B23);

// 第 24 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB24AOE(BossModule module) : HighCrucibleCastAOEs(module, Battle.B24);

// 第 25 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB25AOE(BossModule module) : HighCrucibleCastAOEs(module, Battle.B25);

// 第 26 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB26AOE(BossModule module) : HighCrucibleCastAOEs(module, Battle.B26);

// 第 27 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB27AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B27);

// 第 28 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB28AOE(BossModule module) : HighCrucibleCastAOEs(module, Battle.B28);

// 第 29 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB29AOE(BossModule module) : CrucibleTreantAOEs(module, Battle.B29);

// 第 30 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB30AOE(BossModule module) : HighCrucibleCastAOEs(module, Battle.B30);

// 第 31 组（斗兽奇弈高段 第一盘）
[SkipLocalsInit]
sealed class XBMB31AOE(BossModule module) : HighCrucibleCastAOEs(module, Battle.B31);

// 第 32 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB32AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B32);

// 第 33 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB33AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B33);

// 第 34 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB34AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B34);

// 第 35 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB35AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B35);

// 第 36 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB36AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B36);

// 第 37 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB37AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B37);

// 第 38 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB38AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B38);

// 第 39 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB39AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B39);

// 第 40 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB40AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B40);

// 第 41 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB41AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B41);

// 第 42 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB42AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B42);

// 第 43 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB43AOE(BossModule module) : CrucibleCastAOEs(module, Battle.B43);

// 第 44 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB44AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B44);

// 第 45 组（斗兽奇弈高段 第二盘）
[SkipLocalsInit]
sealed class XBMB45AOE(BossModule module) : High2CrucibleCastAOEs(module, Battle.B45);

// 各组提示组件（击退 / 全体状态 / 视线等），基于 Components.CastHints

// 第 1 组提示：Physical Damage Up (single target)
[SkipLocalsInit]
sealed class XBMB01Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A46871], "Physical Damage Up (single target)");

// 第 3 组提示：Damage Up (single target)
[SkipLocalsInit]
sealed class XBMB03Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A46898], "Damage Up (single target)");

// 第 4 组提示：Poison (single target)
[SkipLocalsInit]
sealed class XBMB04Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A46906], "Poison (single target)");

// 第 6 组提示：Poison (single target)
[SkipLocalsInit]
sealed class XBMB06Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A46935], "Poison (single target)");

// 第 8 组提示：Doom (raidwide)
[SkipLocalsInit]
sealed class XBMB08Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48143, (uint)AID.A48153], "Doom (raidwide)");

// 第 9 组提示：Knockback!
[SkipLocalsInit]
sealed class XBMB09Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48168], "Knockback!");

// 第 12 组提示：Paralysis (single target)
[SkipLocalsInit]
sealed class XBMB12Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48247], "Paralysis (single target)");

// 第 13 组提示：Little Bean Hide (single target)
[SkipLocalsInit]
sealed class XBMB13Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48242], "Little Bean Hide (single target)");

// 第 15 组提示：Paralytic Spike (single target)
[SkipLocalsInit]
sealed class XBMB15Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A50532], "Paralytic Spike (single target)");

// 第 15 组提示：Terror (raidwide)
[SkipLocalsInit]
sealed class XBMB15Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A48485], "Terror (raidwide)");

// 第 16 组提示：Heavy (single target)
[SkipLocalsInit]
sealed class XBMB16Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48489], "Heavy (single target)");

// 第 17 组提示：Petrification (raidwide)
[SkipLocalsInit]
sealed class XBMB17Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48510], "Petrification (raidwide)");

// 第 18 组提示：Blind (raidwide)
[SkipLocalsInit]
sealed class XBMB18Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48561], "Blind (raidwide)");

// 第 18 组提示：Damage Up (single target)
[SkipLocalsInit]
sealed class XBMB18Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A48221], "Damage Up (single target)");

// 第 19 组提示：Bind (single target)
[SkipLocalsInit]
sealed class XBMB19Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48568], "Bind (single target)");

// 第 21 组提示：Knockback!
[SkipLocalsInit]
sealed class XBMB21Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48607], "Knockback!");

// 第 22 组提示：Magic Damage Up (single target)
[SkipLocalsInit]
sealed class XBMB22Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48668], "Magic Damage Up (single target)");

// 第 23 组提示：Heavy (single target)
[SkipLocalsInit]
sealed class XBMB23Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48680], "Heavy (single target)");

// 第 23 组提示：Knockback!
[SkipLocalsInit]
sealed class XBMB23Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A50758], "Knockback!");

// 第 23 组提示：Paralysis (single target)
[SkipLocalsInit]
sealed class XBMB23Hint2(BossModule module) : Components.CastHints(module, [(uint)AID.A50544], "Paralysis (single target)");

// 第 23 组提示：Poison (single target)
[SkipLocalsInit]
sealed class XBMB23Hint3(BossModule module) : Components.CastHints(module, [(uint)AID.A50750], "Poison (single target)");

// 第 24 组提示：Devour (single target)
[SkipLocalsInit]
sealed class XBMB24Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48685], "Devour (single target)");

// 第 27 组提示：Confusion (raidwide)
[SkipLocalsInit]
sealed class XBMB27Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48740], "Confusion (raidwide)");

// 第 27 组提示：Fire Resistance Down (single target)
[SkipLocalsInit]
sealed class XBMB27Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A48742], "Fire Resistance Down (single target)");

// 第 27 组提示：Poison (raidwide)
[SkipLocalsInit]
sealed class XBMB27Hint2(BossModule module) : Components.CastHints(module, [(uint)AID.A48738], "Poison (raidwide)");

// 第 30 组提示：Ice Spikes (single target)
[SkipLocalsInit]
sealed class XBMB30Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48793], "Ice Spikes (single target)");

// 第 31 组提示：Deadly Poison (raidwide)
[SkipLocalsInit]
sealed class XBMB31Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A48821], "Deadly Poison (raidwide)");

// 第 32 组提示：Paralysis (single target)
[SkipLocalsInit]
sealed class XBMB32Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A49189], "Paralysis (single target)");

// 第 33 组提示：Paralysis (raidwide)
[SkipLocalsInit]
sealed class XBMB33Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A49208], "Paralysis (raidwide)");

// 第 33 组提示：Poison (raidwide)
[SkipLocalsInit]
sealed class XBMB33Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A49198], "Poison (raidwide)");

// 第 34 组提示：Blind (raidwide)
[SkipLocalsInit]
sealed class XBMB34Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A49231], "Blind (raidwide)");

// 第 34 组提示：Invisible (raidwide)
[SkipLocalsInit]
sealed class XBMB34Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A49209], "Invisible (raidwide)");

// 第 34 组提示：Petrification (raidwide)
[SkipLocalsInit]
sealed class XBMB34Hint2(BossModule module) : Components.CastHints(module, [(uint)AID.A49214], "Petrification (raidwide)");

// 第 35 组提示：Knockback!
[SkipLocalsInit]
sealed class XBMB35Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A49238, (uint)AID.A49242], "Knockback!");

// 第 35 组提示：Physical Vulnerability Up (single target)
[SkipLocalsInit]
sealed class XBMB35Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A49241], "Physical Vulnerability Up (single target)");

// 第 36 组提示：Confusion (raidwide)
[SkipLocalsInit]
sealed class XBMB36Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A49261], "Confusion (raidwide)");

// 第 36 组提示：Fire Spikes (single target)
[SkipLocalsInit]
sealed class XBMB36Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A49253], "Fire Spikes (single target)");

// 第 36 组提示：Gradual Confusion (single target)
[SkipLocalsInit]
sealed class XBMB36Hint2(BossModule module) : Components.CastHints(module, [(uint)AID.A49260], "Gradual Confusion (single target)");

// 第 36 组提示：Needle Cover (single target)
[SkipLocalsInit]
sealed class XBMB36Hint3(BossModule module) : Components.CastHints(module, [(uint)AID.A49250], "Needle Cover (single target)");

// 第 38 组提示：Damage Up (single target)
[SkipLocalsInit]
sealed class XBMB38Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A49298], "Damage Up (single target)");

// 第 42 组提示：Damage Up (single target)
[SkipLocalsInit]
sealed class XBMB42Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A49394], "Damage Up (single target)");

// 第 42 组提示：Fire Resistance Down (raidwide)
[SkipLocalsInit]
sealed class XBMB42Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A49384], "Fire Resistance Down (raidwide)");

// 第 42 组提示：水属性耐性降低 [5337] (raidwide)
[SkipLocalsInit]
sealed class XBMB42Hint2(BossModule module) : Components.CastHints(module, [(uint)AID.A49385], "水属性耐性降低 [5337] (raidwide)");

// 第 44 组提示：Burns (single target)
[SkipLocalsInit]
sealed class XBMB44Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A49435], "Burns (single target)");

// 第 44 组提示：Doom (raidwide)
[SkipLocalsInit]
sealed class XBMB44Hint1(BossModule module) : Components.CastHints(module, [(uint)AID.A49434], "Doom (raidwide)");

// 第 45 组提示：Knockback!
[SkipLocalsInit]
sealed class XBMB45Hint0(BossModule module) : Components.CastHints(module, [(uint)AID.A49453], "Knockback!");

// 斗兽奇弈模块基类。
// - 场地：目前未知，先跟随玩家（半径 40y），开服实测后再固定中心/边界。
// - OID 目前用 BNpcName 行号占位，所以额外用 NameID / 名字做一次校验，避免占位 OID
//   在其他内容里撞到同名 Actor 时误触发。
[SkipLocalsInit]
public abstract class CrucibleModule(WorldState ws, Actor primary, uint expectedNameID)
    : BossModule(ws, primary, primary.Position, new ArenaBoundsCircle(40f, AllowObstacleMap: true))
{
    private readonly uint _expectedNameID = expectedNameID;

    // 本组任意同名敌人还在战斗就不重置（主 Actor 可能只是同组的一个分身）
    public override bool CheckReset()
    {
        foreach (var a in WorldState.Actors)
        {
            if (a.NameID == _expectedNameID && a.InCombat && !a.IsDeadOrDestroyed)
            {
                return false;
            }
        }
        return true;
    }

    // 本组的唯一实体或任意同名复制体进入战斗即激活（复制体是 OID 9020，模块只注册在唯一实体上）
    protected override bool CheckPull()
    {
        if (PrimaryActor.NameID == _expectedNameID && PrimaryActor.IsTargetable && PrimaryActor.InCombat)
        {
            return true;
        }
        foreach (var a in WorldState.Actors)
        {
            if (a.NameID == _expectedNameID && a.IsTargetable && a.InCombat && !a.IsDead)
            {
                return true;
            }
        }
        return false;
    }

    // 场地中心：本组敌人的质心。ARR 实测每组敌人固定刷在一个 ~30x30 的区域里，
    // 不同组的坐标互不相同（例如组1在 x≈120 z≈-428，组6在 x≈520 z≈-420），
    // 所以不能写死中心；没有活着的敌人时退回玩家位置。
    protected override void UpdateModule()
    {
        var x = 0f;
        var z = 0f;
        var n = 0;
        foreach (var a in WorldState.Actors)
        {
            if (a.NameID == _expectedNameID && !a.IsDeadOrDestroyed)
            {
                x += a.Position.X;
                z += a.Position.Z;
                ++n;
            }
        }
        Arena.Center = n > 0 ? new WPos(x / n, z / n) : (Raid.Player()?.Position ?? PrimaryActor.Position);
    }

    protected override void CalculateModuleAIHints(int slot, Actor actor, PartyRolesConfig.Assignment assignment, AIHints hints)
    {
        hints.PathfindMapCenter = Arena.Center;
        hints.PathfindMapBounds = Arena.Bounds;
    }
}
