// <auto-generated>
// 斗兽奇弈：真实 OID 运行时映射。
// 客户端表 BNpcBase 没有名字链接，无法静态推出 Actor.OID，所以模块先用哨兵 OID 注册，
// 由 BossModuleManager.ActorAdded -> CrucibleOIDResolver.TryRegister 按 NameID/名字
// 把真实 OID 映射到对应模块。首次进入斗兽奇弈即可正常加载，也不会与现有模块抢 OID。
// </auto-generated>
namespace BossMod.Dawntrail.Foray.Crucible;

public static class CrucibleOIDResolver
{
    // BNpcName 行号 -> 战斗模块类型
    private static readonly Dictionary<uint, Type> _byNameID = new()
    {
        [14531] = typeof(XBMB01),
        [14532] = typeof(XBMB01),
        [14533] = typeof(XBMB02),
        [14535] = typeof(XBMB03),
        [14536] = typeof(XBMB04),
        [14537] = typeof(XBMB04),
        [14538] = typeof(XBMB05),
        [14539] = typeof(XBMB05),
        [14748] = typeof(XBMB05),
        [14541] = typeof(XBMB06),
        [14542] = typeof(XBMB06),
        [14543] = typeof(XBMB06),
        [14557] = typeof(XBMB12),
        [14558] = typeof(XBMB12),
        [14559] = typeof(XBMB12),
        [14545] = typeof(XBMB07),
        [14555] = typeof(XBMB11),
        [14556] = typeof(XBMB11),
        [14549] = typeof(XBMB09),
        [14581] = typeof(XBMB18),
        [14580] = typeof(XBMB18),
        [14552] = typeof(XBMB10),
        [14546] = typeof(XBMB08),
        [14548] = typeof(XBMB08),
        [14561] = typeof(XBMB13),
        [14562] = typeof(XBMB13),
        [14587] = typeof(XBMB20),
        [14591] = typeof(XBMB20),
        [14590] = typeof(XBMB20),
        [14589] = typeof(XBMB20),
        [14569] = typeof(XBMB15),
        [14571] = typeof(XBMB15),
        [14577] = typeof(XBMB17),
        [14583] = typeof(XBMB19),
        [14586] = typeof(XBMB19),
        [14585] = typeof(XBMB19),
        [14572] = typeof(XBMB16),
        [14574] = typeof(XBMB16),
        [14592] = typeof(XBMB21),
        [14595] = typeof(XBMB21),
        [14624] = typeof(XBMB30),
        [14623] = typeof(XBMB30),
        [14625] = typeof(XBMB30),
        [14626] = typeof(XBMB30),
        [14627] = typeof(XBMB30),
        [14651] = typeof(XBMB36),
        [14653] = typeof(XBMB36),
        [14656] = typeof(XBMB36),
        [14608] = typeof(XBMB26),
        [14603] = typeof(XBMB24),
        [14605] = typeof(XBMB24),
        [14564] = typeof(XBMB14),
        [14567] = typeof(XBMB14),
        [14596] = typeof(XBMB22),
        [14612] = typeof(XBMB27),
        [14616] = typeof(XBMB27),
        [14613] = typeof(XBMB27),
        [14610] = typeof(XBMB27),
        [14614] = typeof(XBMB27),
        [14641] = typeof(XBMB34),
        [14640] = typeof(XBMB34),
        [14639] = typeof(XBMB34),
        [14638] = typeof(XBMB34),
        [14628] = typeof(XBMB31),
        [14629] = typeof(XBMB31),
        [14657] = typeof(XBMB37),
        [14659] = typeof(XBMB37),
        [14618] = typeof(XBMB29),
        [14620] = typeof(XBMB29),
        [14621] = typeof(XBMB29),
        [14622] = typeof(XBMB29),
        [14619] = typeof(XBMB29),
        [14663] = typeof(XBMB39),
        [14664] = typeof(XBMB39),
        [14599] = typeof(XBMB23),
        [14601] = typeof(XBMB23),
        [14602] = typeof(XBMB23),
        [14600] = typeof(XBMB23),
        [14693] = typeof(XBMB45),
        [14699] = typeof(XBMB45),
        [14606] = typeof(XBMB25),
        [14607] = typeof(XBMB25),
        [14617] = typeof(XBMB28),
        [14670] = typeof(XBMB41),
        [14671] = typeof(XBMB41),
        [14673] = typeof(XBMB41),
        [14672] = typeof(XBMB41),
        [14631] = typeof(XBMB32),
        [14632] = typeof(XBMB32),
        [14633] = typeof(XBMB33),
        [14634] = typeof(XBMB33),
        [14642] = typeof(XBMB35),
        [14643] = typeof(XBMB35),
        [14644] = typeof(XBMB35),
        [14646] = typeof(XBMB35),
        [14645] = typeof(XBMB35),
        [14647] = typeof(XBMB35),
        [14648] = typeof(XBMB35),
        [14649] = typeof(XBMB35),
        [14660] = typeof(XBMB38),
        [14661] = typeof(XBMB38),
        [14662] = typeof(XBMB38),
        [14675] = typeof(XBMB42),
        [14676] = typeof(XBMB42),
        [14677] = typeof(XBMB42),
        [14683] = typeof(XBMB42),
        [14680] = typeof(XBMB42),
        [14679] = typeof(XBMB42),
        [14678] = typeof(XBMB42),
        [14681] = typeof(XBMB42),
        [14665] = typeof(XBMB40),
        [14684] = typeof(XBMB43),
        [14685] = typeof(XBMB43),
        [14686] = typeof(XBMB43),
        [14688] = typeof(XBMB44),
        [14691] = typeof(XBMB44),
        [14692] = typeof(XBMB44),
    };

    // 敌人名字 -> 战斗模块类型（NameID 对不上时的兜底；同名取第一次出现）
    private static readonly Dictionary<string, Type> _byName = new(StringComparer.Ordinal)
    {
        ["奇子·骑士"] = typeof(XBMB01),
        ["奇子·主教"] = typeof(XBMB01),
        ["奇子·上级恶魔"] = typeof(XBMB02),
        ["奇子·夺灵魔"] = typeof(XBMB03),
        ["奇子·祸蛛蝎"] = typeof(XBMB04),
        ["奇子·灵蛛蝎"] = typeof(XBMB04),
        ["奇子·食人魔"] = typeof(XBMB05),
        ["奇子·妖火"] = typeof(XBMB05),
        ["奇子·大妖火"] = typeof(XBMB05),
        ["魅惑女妖 帕德索"] = typeof(XBMB06),
        ["奇子·梦魔法师"] = typeof(XBMB06),
        ["奇子·梦魔骑士"] = typeof(XBMB06),
        ["奇子·恶魔"] = typeof(XBMB12),
        ["奇子·恶魔兵装"] = typeof(XBMB12),
        ["奇子·小恶魔"] = typeof(XBMB12),
        ["奇子·曼提克"] = typeof(XBMB07),
        ["奇子·牛魔老哥"] = typeof(XBMB11),
        ["奇子·牛魔老弟"] = typeof(XBMB11),
        ["奇子·双足飞龙"] = typeof(XBMB09),
        ["奇子·巨像"] = typeof(XBMB18),
        ["奇子·拉哈穆"] = typeof(XBMB18),
        ["奇子·虚灵法师"] = typeof(XBMB10),
        ["奇子·牛头魔"] = typeof(XBMB08),
        ["奇子·冥鬼之眼"] = typeof(XBMB08),
        ["寻兽探奇 路斯福洛克斯"] = typeof(XBMB13),
        ["小地豆"] = typeof(XBMB13),
        ["奇子·勇士"] = typeof(XBMB20),
        ["奇子·守卫"] = typeof(XBMB20),
        ["奇子·士兵"] = typeof(XBMB20),
        ["奇子·仙人花"] = typeof(XBMB20),
        ["奇子·尤弥尔"] = typeof(XBMB15),
        ["奇子·鱼人"] = typeof(XBMB15),
        ["奇子·卡托布莱帕斯"] = typeof(XBMB17),
        ["奇子·塞壬"] = typeof(XBMB19),
        ["奇子·爬行鬼"] = typeof(XBMB19),
        ["奇子·蹒跚鬼"] = typeof(XBMB19),
        ["奇子·祖"] = typeof(XBMB16),
        ["奇子·母雏鸟"] = typeof(XBMB16),
        ["贪食无厌 加特勒"] = typeof(XBMB21),
        ["奇子·塔纳托斯"] = typeof(XBMB21),
        ["奇子·榴弹怪"] = typeof(XBMB30),
        ["奇子·爆弹之母"] = typeof(XBMB30),
        ["奇子·爆弹怪"] = typeof(XBMB30),
        ["奇子·雪弹怪"] = typeof(XBMB30),
        ["奇子·焰球"] = typeof(XBMB30),
        ["奇子·火蛟"] = typeof(XBMB36),
        ["奇子·棘鼹"] = typeof(XBMB36),
        ["奇子·蓝闪蝶"] = typeof(XBMB36),
        ["奇子·石像鬼"] = typeof(XBMB26),
        ["奇子·尸生花"] = typeof(XBMB24),
        ["奇子·女王鹰蜂"] = typeof(XBMB24),
        ["奇子·游侠骑士"] = typeof(XBMB14),
        ["奇子·博学林鸮"] = typeof(XBMB22),
        ["奇子·发条步兵"] = typeof(XBMB27),
        ["奇子·眼镜蛇"] = typeof(XBMB27),
        ["奇子·恐慌装甲"] = typeof(XBMB27),
        ["奇子·管理者"] = typeof(XBMB27),
        ["奇子·无人机"] = typeof(XBMB27),
        ["光元精"] = typeof(XBMB34),
        ["奇子·深瞳"] = typeof(XBMB34),
        ["奇子·夜魔人"] = typeof(XBMB34),
        ["怨毒龙 博尔格尼"] = typeof(XBMB31),
        ["有毒物质"] = typeof(XBMB31),
        ["奇子·杜尔迦"] = typeof(XBMB37),
        ["奇子·转盘堡"] = typeof(XBMB37),
        ["奇子·树精"] = typeof(XBMB29),
        ["奇子·花苗"] = typeof(XBMB29),
        ["奇子·凶蛛蝎"] = typeof(XBMB29),
        ["奇子·比洛克"] = typeof(XBMB29),
        ["奇子·蛞蝓"] = typeof(XBMB29),
        ["奇子·奇美拉"] = typeof(XBMB39),
        ["奇子·魔界花"] = typeof(XBMB23),
        ["奇子·大口花"] = typeof(XBMB23),
        ["腐汁"] = typeof(XBMB23),
        ["奇子·幼苗"] = typeof(XBMB23),
        ["魔斧之主 劳妲"] = typeof(XBMB45),
        ["奇子·冰龙"] = typeof(XBMB25),
        ["冰元精"] = typeof(XBMB25),
        ["奇子·巨人"] = typeof(XBMB41),
        ["奇子·独眼巨人"] = typeof(XBMB41),
        ["凝胶化火焰"] = typeof(XBMB41),
        ["凝胶化雷电"] = typeof(XBMB41),
        ["奇子·佛劳洛斯"] = typeof(XBMB32),
        ["雷元精"] = typeof(XBMB32),
        ["奇子·夺心魔"] = typeof(XBMB33),
        ["奇子·毒性魔菇"] = typeof(XBMB33),
        ["奇子·阿托莫斯"] = typeof(XBMB35),
        ["奇子·红格雷姆林"] = typeof(XBMB35),
        ["奇子·奶冻怪"] = typeof(XBMB35),
        ["奇子·软糊怪"] = typeof(XBMB35),
        ["奇子·甜羹怪"] = typeof(XBMB35),
        ["奇子·石像魔"] = typeof(XBMB35),
        ["奇子·威胁扎哈克"] = typeof(XBMB35),
        ["奇子·美杜莎"] = typeof(XBMB38),
        ["奇子·拉米亚"] = typeof(XBMB38),
        ["奇子·莫古小猛"] = typeof(XBMB42),
        ["奇子·莫古大医"] = typeof(XBMB42),
        ["奇子·莫古大术"] = typeof(XBMB42),
        ["奇子·莫古小贼"] = typeof(XBMB42),
        ["奇子·莫古大剑"] = typeof(XBMB42),
        ["奇子·莫古小术"] = typeof(XBMB42),
        ["奇子·莫古小医"] = typeof(XBMB42),
        ["奇子·莫古小歌"] = typeof(XBMB42),
        ["奇子·斯芬克斯"] = typeof(XBMB40),
        ["奇子·贝希摩斯"] = typeof(XBMB43),
        ["奇子·铁巨人"] = typeof(XBMB43),
        ["奇子·冥鬼之眼王"] = typeof(XBMB44),
        ["奇子·哈帕利特"] = typeof(XBMB44),
        ["奇子·肮脏之眼"] = typeof(XBMB44),
    };

    // 斗兽奇弈的“奇子”通用复制体 OID：同组会刷很多个，不能让它抢注册
    internal const uint DummyOID = 9020u;

    internal static bool MatchesGroup(Actor actor, uint primaryNameID) =>
        _byNameID.TryGetValue(primaryNameID, out var group) && Lookup(actor) == group;

    // 每次有新 Actor 进入世界时调用（在模块创建之前）
    public static void TryRegister(Actor actor)
    {
        if (actor.OID == DummyOID || actor.Type is not ActorType.Enemy and not ActorType.EventObj)
        {
            return;
        }
        var type = Lookup(actor);
        if (type == null)
        {
            return;
        }
        // 9020 被多组机制分身共用，即使先于实体出现也不能写入全局 OID 注册表。
        // FindByType 会先触发 BossModuleRegistry 静态构造（注册所有模块的主 OID），
        // 之后才能安全检查该 OID 是否已被占用。
        var info = BossModuleRegistry.FindByType(type);
        if (info == null)
        {
            return;
        }
        if (BossModuleRegistry.RegisteredModules.TryGetValue(actor.OID, out var existing))
        {
            if (existing.ModuleType != type)
            {
                return; // 已被其他模块占用，不抢
            }
            return;
        }
        BossModuleRegistry.RegisteredModules[actor.OID] = info;
        Service.Log($"[Crucible] OID 0x{actor.OID:X} -> {type.Name} (NameID {actor.NameID} '{actor.Name}')");
    }

    private static Type Lookup(Actor actor)
    {
        if (_byNameID.TryGetValue(actor.NameID, out var byID))
        {
            return byID;
        }
        var name = actor.Name;
        if (name.Length == 0)
        {
            return null;
        }
        foreach (var (key, type) in _byName)
        {
            if (name.Contains(key, StringComparison.Ordinal))
            {
                return type;
            }
        }
        return null;
    }
}
