// <auto-generated>
// 斗兽奇弈：每组敌人一个模块（共 45 组）。
// 已录制组使用实测主 OID；其余组保留哨兵 OID，等待实录核对。
// </auto-generated>
namespace BossMod.Dawntrail.Foray.Crucible;

// 第 1 组（斗兽奇弈 第一盘）：奇子·骑士 + 奇子·主教[14532]
[SkipLocalsInit]
sealed class XBMB01States : RecordedCrucibleStates
{
    public XBMB01States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB01AOE>()
            .ActivateOnEnter<XBMB01Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB01States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14531,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14531u, // 奇子·骑士
    SortOrder = 1)]
[SkipLocalsInit]
public sealed class XBMB01(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14531u);

// 第 2 组（斗兽奇弈 第一盘）：奇子·上级恶魔
[SkipLocalsInit]
sealed class XBMB02States : RecordedCrucibleStates
{
    public XBMB02States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB02AOE>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB02States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14533,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14533u, // 奇子·上级恶魔
    SortOrder = 2)]
[SkipLocalsInit]
public sealed class XBMB02(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14533u);

// 第 3 组（斗兽奇弈 第一盘）：奇子·夺灵魔
[SkipLocalsInit]
sealed class XBMB03States : RecordedCrucibleStates
{
    public XBMB03States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB03AOE>()
            .ActivateOnEnter<CrucibleVoidBlizzard>()
            .ActivateOnEnter<CrucibleVoidFlare>()
            .ActivateOnEnter<CrucibleVoidFlareHint>()
            .ActivateOnEnter<XBMB03Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB03States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14535,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14535u, // 奇子·夺灵魔
    SortOrder = 3)]
[SkipLocalsInit]
public sealed class XBMB03(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14535u);

// 第 4 组（斗兽奇弈 第一盘）：奇子·祸蛛蝎 + 奇子·灵蛛蝎[14537]
[SkipLocalsInit]
sealed class XBMB04States : RecordedCrucibleStates
{
    public XBMB04States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB04AOE>()
            .ActivateOnEnter<CrucibleGroundUpliftAOEs>()
            .ActivateOnEnter<CrucibleWebAOEs>()
            .ActivateOnEnter<XBMB04Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB04States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14536,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14536u, // 奇子·祸蛛蝎
    SortOrder = 4)]
[SkipLocalsInit]
public sealed class XBMB04(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14536u);

// 第 5 组（斗兽奇弈 第一盘）：奇子·食人魔 + 奇子·妖火[14539], 奇子·大妖火[14748]
[SkipLocalsInit]
sealed class XBMB05States : RecordedCrucibleStates
{
    public XBMB05States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB05AOE>()
            .ActivateOnEnter<CrucibleLava>()
            .ActivateOnEnter<CrucibleFireSpiritWard>()
            .ActivateOnEnter<CrucibleFireball>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB05States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14538,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14538u, // 奇子·食人魔
    SortOrder = 5)]
[SkipLocalsInit]
public sealed class XBMB05(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14538u);

// 第 6 组（斗兽奇弈 第一盘）：魅惑女妖 帕德索 + 奇子·梦魔法师[14542], 奇子·梦魔骑士[14543]
[SkipLocalsInit]
sealed class XBMB06States : RecordedCrucibleStates
{
    public XBMB06States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB06AOE>()
            .ActivateOnEnter<XBMB06Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB06States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14541,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14541u, // 魅惑女妖 帕德索
    SortOrder = 6)]
[SkipLocalsInit]
public sealed class XBMB06(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14541u);

// 第 12 组（斗兽奇弈 第二盘）：奇子·恶魔 + 奇子·恶魔兵装[14558], 奇子·小恶魔[14559]
[SkipLocalsInit]
sealed class XBMB12States : StateMachineBuilder
{
    public XBMB12States(BossModule module) : base(module)
    {
        TrivialPhase()
            .ActivateOnEnter<XBMB12AOE>()
            .ActivateOnEnter<XBMB12Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB12States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14557,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14557u, // 奇子·恶魔
    SortOrder = 12)]
[SkipLocalsInit]
public sealed class XBMB12(WorldState ws, Actor primary) : CrucibleModule(ws, primary, 14557u);

// 第 7 组（斗兽奇弈 第二盘）：奇子·曼提克
[SkipLocalsInit]
sealed class XBMB07States : RecordedCrucibleStates
{
    public XBMB07States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB07AOE>()
            .ActivateOnEnter<CrucibleManticoreHalfArena>()
            .ActivateOnEnter<CrucibleManticoreCharges>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB07States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14545,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14545u, // 奇子·曼提克
    SortOrder = 7)]
[SkipLocalsInit]
public sealed class XBMB07(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14545u);

// 第 11 组（斗兽奇弈 第二盘）：奇子·牛魔老哥 + 奇子·牛魔老弟[14556]
[SkipLocalsInit]
sealed class XBMB11States : RecordedCrucibleStates
{
    public XBMB11States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB11AOE>()
            .ActivateOnEnter<CrucibleMinotaurSequence>()
            .ActivateOnEnter<CrucibleMinotaurStomp>()
            .ActivateOnEnter<CrucibleMinotaurRotation>()
            .ActivateOnEnter<CrucibleMinotaurEnrageHint>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB11States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14555,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14555u, // 奇子·牛魔老哥
    SortOrder = 11)]
[SkipLocalsInit]
public sealed class XBMB11(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14555u);

// 第 9 组（斗兽奇弈 第二盘）：奇子·双足飞龙
[SkipLocalsInit]
sealed class XBMB09States : RecordedCrucibleStates
{
    public XBMB09States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB09AOE>()
            .ActivateOnEnter<CrucibleLiquidHell>()
            .ActivateOnEnter<CrucibleTyphoon>()
            .ActivateOnEnter<CrucibleTornadoes>()
            .ActivateOnEnter<XBMB09Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB09States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14549,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14549u, // 奇子·双足飞龙
    SortOrder = 9)]
[SkipLocalsInit]
public sealed class XBMB09(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14549u);

// 第 18 组（斗兽奇弈 第三盘）：奇子·巨像 + 奇子·拉哈穆[14580]
[SkipLocalsInit]
sealed class XBMB18States : RecordedCrucibleStates
{
    public XBMB18States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB18AOE>()
            .ActivateOnEnter<CrucibleLahamuKnockback>()
            .ActivateOnEnter<CrucibleLahamuGolems>()
            .ActivateOnEnter<CrucibleLahamuSand>()
            .ActivateOnEnter<CrucibleLahamuEarthshakerHint>()
            .ActivateOnEnter<XBMB18Hint0>()
            .ActivateOnEnter<XBMB18Hint1>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB18States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14581,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14581u, // 奇子·巨像
    SortOrder = 18)]
[SkipLocalsInit]
public sealed class XBMB18(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14581u);

// 第 10 组（斗兽奇弈 第二盘）：奇子·虚灵法师
[SkipLocalsInit]
sealed class XBMB10States : RecordedCrucibleStates
{
    public XBMB10States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB10AOE>()
            .ActivateOnEnter<CrucibleZombies>()
            .ActivateOnEnter<CrucibleNecromist>()
            .ActivateOnEnter<CrucibleDeathDrive>()
            .ActivateOnEnter<CrucibleNecromancerMarch>()
            .ActivateOnEnter<CrucibleNecromancerHint>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB10States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14552,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14552u, // 奇子·虚灵法师
    SortOrder = 10)]
[SkipLocalsInit]
public sealed class XBMB10(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14552u);

// 第 8 组（斗兽奇弈 第二盘）：奇子·牛头魔 + 奇子·冥鬼之眼[14548]
[SkipLocalsInit]
sealed class XBMB08States : RecordedCrucibleStates
{
    public XBMB08States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB08AOE>()
            .ActivateOnEnter<XBMB08Hint0>()
            .ActivateOnEnter<CrucibleTaurusExplosions>()
            .ActivateOnEnter<CrucibleTaurusDarkRay>()
            .ActivateOnEnter<CrucibleTaurusGaze>()
            .ActivateOnEnter<CrucibleTaurusStare>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB08States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14546,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14546u, // 奇子·牛头魔
    SortOrder = 8)]
[SkipLocalsInit]
public sealed class XBMB08(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14546u);

// 第 13 组（斗兽奇弈 第二盘）：寻兽探奇 路斯福洛克斯 + 小地豆[14562]
[SkipLocalsInit]
sealed class XBMB13States : RecordedCrucibleStates
{
    public XBMB13States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB13AOE>()
            .ActivateOnEnter<CrucibleSandpits>()
            .ActivateOnEnter<CrucibleGoblinBombs>()
            .ActivateOnEnter<CrucibleSandPillars>()
            .ActivateOnEnter<CrucibleWormQuakeHint>()
            .ActivateOnEnter<XBMB13Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB13States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14561,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14561u, // 寻兽探奇 路斯福洛克斯
    SortOrder = 13)]
[SkipLocalsInit]
public sealed class XBMB13(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14561u);

// 第 20 组（斗兽奇弈 第三盘）：奇子·勇士 + 奇子·守卫[14591], 奇子·士兵[14590], 奇子·仙人花[14589]
[SkipLocalsInit]
sealed class XBMB20States : StateMachineBuilder
{
    public XBMB20States(BossModule module) : base(module)
    {
        TrivialPhase()
            .ActivateOnEnter<XBMB20AOE>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB20States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14587,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14587u, // 奇子·勇士
    SortOrder = 20)]
[SkipLocalsInit]
public sealed class XBMB20(WorldState ws, Actor primary) : CrucibleModule(ws, primary, 14587u);

// 第 15 组（斗兽奇弈 第三盘）：奇子·尤弥尔 + 奇子·鱼人[14571]
[SkipLocalsInit]
sealed class XBMB15States : RecordedCrucibleStates
{
    public XBMB15States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB15AOE>()
            .ActivateOnEnter<CrucibleYmirThunderHint>()
            .ActivateOnEnter<CrucibleYmirRocks>()
            .ActivateOnEnter<CrucibleYmirTargets>()
            .ActivateOnEnter<CrucibleYmirTsunami>()
            .ActivateOnEnter<XBMB15Hint0>()
            .ActivateOnEnter<XBMB15Hint1>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB15States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14569,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14569u, // 奇子·尤弥尔
    SortOrder = 15)]
[SkipLocalsInit]
public sealed class XBMB15(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14569u);

// 第 17 组（斗兽奇弈 第三盘）：奇子·卡托布莱帕斯
[SkipLocalsInit]
sealed class XBMB17States : RecordedCrucibleStates
{
    public XBMB17States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB17AOE>()
            .ActivateOnEnter<CrucibleCatoblepasEyes>()
            .ActivateOnEnter<CrucibleCatoblepasGaze>()
            .ActivateOnEnter<XBMB17Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB17States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14577,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14577u, // 奇子·卡托布莱帕斯
    SortOrder = 17)]
[SkipLocalsInit]
public sealed class XBMB17(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14577u);

// 第 19 组（斗兽奇弈 第三盘）：奇子·塞壬 + 奇子·爬行鬼[14586], 奇子·蹒跚鬼[14585]
[SkipLocalsInit]
sealed class XBMB19States : RecordedCrucibleStates
{
    public XBMB19States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB19AOE>()
            .ActivateOnEnter<CrucibleSirenSong>()
            .ActivateOnEnter<CrucibleSirenExplosions>()
            .ActivateOnEnter<XBMB19Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB19States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14583,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14583u, // 奇子·塞壬
    SortOrder = 19)]
[SkipLocalsInit]
public sealed class XBMB19(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14583u);

// 第 16 组（斗兽奇弈 第三盘）：奇子·祖 + 奇子·母雏鸟[14574]
[SkipLocalsInit]
sealed class XBMB16States : RecordedCrucibleStates
{
    public XBMB16States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB16AOE>()
            .ActivateOnEnter<CrucibleZuCrossHint>()
            .ActivateOnEnter<CrucibleZuFrenzyHint>()
            .ActivateOnEnter<CrucibleZuRear>()
            .ActivateOnEnter<XBMB16Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB16States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14572,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14572u, // 奇子·祖
    SortOrder = 16)]
[SkipLocalsInit]
public sealed class XBMB16(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14572u);

// 第 21 组（斗兽奇弈 第三盘）：贪食无厌 加特勒 + 奇子·塔纳托斯[14595]
[SkipLocalsInit]
sealed class XBMB21States : RecordedCrucibleStates
{
    public XBMB21States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB21AOE>()
            .ActivateOnEnter<CrucibleGatlerTorrent>()
            .ActivateOnEnter<CrucibleGatlerExplosions>()
            .ActivateOnEnter<CrucibleGatlerTraps>()
            .ActivateOnEnter<CrucibleGatlerBait>()
            .ActivateOnEnter<CrucibleGatlerFireKnife>()
            .ActivateOnEnter<CrucibleGatlerThunder>()
            .ActivateOnEnter<XBMB21Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB21States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14592,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14592u, // 贪食无厌 加特勒
    SortOrder = 21)]
[SkipLocalsInit]
public sealed class XBMB21(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14592u);

// 第 30 组（斗兽奇弈高段 第一盘）：奇子·榴弹怪 + 奇子·爆弹之母[14623], 奇子·爆弹怪[14625], 奇子·雪弹怪[14626], 奇子·焰球[14627]
[SkipLocalsInit]
sealed class XBMB30States : RecordedCrucibleStates
{
    public XBMB30States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB30AOE>()
            .ActivateOnEnter<CrucibleMovingBombs>()
            .ActivateOnEnter<CrucibleBombPools>()
            .ActivateOnEnter<CrucibleBombMeltdown>()
            .ActivateOnEnter<CrucibleBombMeltdownKnockback>()
            .ActivateOnEnter<CrucibleBombFuryAOEs>()
            .ActivateOnEnter<CrucibleBombFuryKnockback>()
            .ActivateOnEnter<CrucibleBombEnrageHint>()
            .ActivateOnEnter<XBMB30Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB30States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14624,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14624u, // 奇子·榴弹怪
    SortOrder = 30)]
[SkipLocalsInit]
public sealed class XBMB30(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14624u);

// 第 36 组（斗兽奇弈高段 第二盘）：奇子·火蛟 + 奇子·棘鼹[14653], 奇子·蓝闪蝶[14656]
[SkipLocalsInit]
sealed class XBMB36States : StateMachineBuilder
{
    public XBMB36States(BossModule module) : base(module)
    {
        TrivialPhase()
            .ActivateOnEnter<XBMB36AOE>()
            .ActivateOnEnter<XBMB36Hint0>()
            .ActivateOnEnter<XBMB36Hint1>()
            .ActivateOnEnter<XBMB36Hint2>()
            .ActivateOnEnter<XBMB36Hint3>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB36States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14651,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14651u, // 奇子·火蛟
    SortOrder = 36)]
[SkipLocalsInit]
public sealed class XBMB36(WorldState ws, Actor primary) : CrucibleModule(ws, primary, 14651u);

// 第 26 组（斗兽奇弈高段 第一盘）：奇子·石像鬼
[SkipLocalsInit]
sealed class XBMB26States : RecordedCrucibleStates
{
    public XBMB26States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB26AOE>()
            .ActivateOnEnter<CrucibleGargoyleInOut>()
            .ActivateOnEnter<CrucibleGargoyleCharge>()
            .ActivateOnEnter<CrucibleMiasma>()
            .ActivateOnEnter<CrucibleGargoyleKnockback>()
            .ActivateOnEnter<CrucibleGargoyleSlashHint>()
            .ActivateOnEnter<CrucibleGargoyleRingHint>()
            .ActivateOnEnter<CrucibleGargoyleKnockbackHint>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB26States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14608,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14608u, // 奇子·石像鬼
    SortOrder = 26)]
[SkipLocalsInit]
public sealed class XBMB26(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14608u);

// 第 24 组（斗兽奇弈高段 第一盘）：奇子·尸生花 + 奇子·女王鹰蜂[14605]
[SkipLocalsInit]
sealed class XBMB24States : RecordedCrucibleStates
{
    public XBMB24States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB24AOE>()
            .ActivateOnEnter<CrucibleMorbolTether>()
            .ActivateOnEnter<CrucibleRottenStench>()
            .ActivateOnEnter<CrucibleFlowerTrapHint>()
            .ActivateOnEnter<XBMB24Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB24States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14603,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14603u, // 奇子·尸生花
    SortOrder = 24)]
[SkipLocalsInit]
public sealed class XBMB24(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14603u);

// 第 14 组（斗兽奇弈 第三盘）：奇子·游侠骑士 + 奇子·主教[14567]
[SkipLocalsInit]
sealed class XBMB14States : RecordedCrucibleStates
{
    public XBMB14States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB14AOE>()
            .ActivateOnEnter<CrucibleRangerKnockback>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB14States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14564,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14564u, // 奇子·游侠骑士
    SortOrder = 14)]
[SkipLocalsInit]
public sealed class XBMB14(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14564u);

// 第 22 组（斗兽奇弈高段 第一盘）：奇子·博学林鸮
[SkipLocalsInit]
sealed class XBMB22States : RecordedCrucibleStates
{
    public XBMB22States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB22AOE>()
            .ActivateOnEnter<CrucibleOwlTether>()
            .ActivateOnEnter<CrucibleOwlGust>()
            .ActivateOnEnter<CrucibleOwlGustPriority>()
            .ActivateOnEnter<CrucibleOwlGustHint>()
            .ActivateOnEnter<CrucibleOwlChapterHint>()
            .ActivateOnEnter<CrucibleOwlChapters>()
            .ActivateOnEnter<XBMB22Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB22States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14596,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14596u, // 奇子·博学林鸮
    SortOrder = 22)]
[SkipLocalsInit]
public sealed class XBMB22(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14596u);

// 第 27 组（斗兽奇弈高段 第一盘）：奇子·发条步兵 + 奇子·眼镜蛇[14616], 奇子·恐慌装甲[14613], 奇子·管理者[14610], 奇子·无人机[14614]
[SkipLocalsInit]
sealed class XBMB27States : StateMachineBuilder
{
    public XBMB27States(BossModule module) : base(module)
    {
        TrivialPhase()
            .ActivateOnEnter<XBMB27AOE>()
            .ActivateOnEnter<XBMB27Hint0>()
            .ActivateOnEnter<XBMB27Hint1>()
            .ActivateOnEnter<XBMB27Hint2>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB27States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14612,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14612u, // 奇子·发条步兵
    SortOrder = 27)]
[SkipLocalsInit]
public sealed class XBMB27(WorldState ws, Actor primary) : CrucibleModule(ws, primary, 14612u);

// 第 34 组（斗兽奇弈高段 第二盘）：光元精 + 奇子·爆弹怪[14640], 奇子·深瞳[14639], 奇子·夜魔人[14638]
[SkipLocalsInit]
sealed class XBMB34States : StateMachineBuilder
{
    public XBMB34States(BossModule module) : base(module)
    {
        TrivialPhase()
            .ActivateOnEnter<XBMB34AOE>()
            .ActivateOnEnter<XBMB34Hint0>()
            .ActivateOnEnter<XBMB34Hint1>()
            .ActivateOnEnter<XBMB34Hint2>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB34States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14641,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14641u, // 光元精
    SortOrder = 34)]
[SkipLocalsInit]
public sealed class XBMB34(WorldState ws, Actor primary) : CrucibleModule(ws, primary, 14641u);

// 第 31 组（斗兽奇弈高段 第一盘）：怨毒龙 博尔格尼 + 有毒物质[14629]
[SkipLocalsInit]
sealed class XBMB31States : RecordedCrucibleStates
{
    public XBMB31States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB31AOE>()
            .ActivateOnEnter<CrucibleDragonWaves>()
            .ActivateOnEnter<CrucibleDragonPoison>()
            .ActivateOnEnter<CrucibleDragonBaits>()
            .ActivateOnEnter<CrucibleDragonClouds>()
            .ActivateOnEnter<CrucibleDragonLanding>()
            .ActivateOnEnter<CrucibleDragonBreathHint>()
            .ActivateOnEnter<CrucibleDragonLandingHint>()
            .ActivateOnEnter<XBMB31Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB31States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14628,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14628u, // 怨毒龙 博尔格尼
    SortOrder = 31)]
[SkipLocalsInit]
public sealed class XBMB31(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14628u);

// 第 37 组（斗兽奇弈高段 第二盘）：奇子·杜尔迦 + 奇子·转盘堡[14659]
[SkipLocalsInit]
sealed class XBMB37States : RecordedCrucibleStates
{
    public XBMB37States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB37AOE>()
            .ActivateOnEnter<CrucibleDurgaEdgeKnockback>()
            .ActivateOnEnter<CrucibleDurgaRayHint>()
            .ActivateOnEnter<CrucibleDurgaAdds>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB37States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14657,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14657u, // 奇子·杜尔迦
    SortOrder = 37)]
[SkipLocalsInit]
public sealed class XBMB37(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14657u);

// 第 29 组（斗兽奇弈高段 第一盘）：奇子·树精 + 奇子·花苗[14620], 奇子·凶蛛蝎[14621], 奇子·比洛克[14622], 奇子·蛞蝓[14619]
[SkipLocalsInit]
sealed class XBMB29States : RecordedCrucibleStates
{
    public XBMB29States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB29AOE>()
            .ActivateOnEnter<CrucibleTreantBody>()
            .ActivateOnEnter<CrucibleGroveAdds>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB29States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14618,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14618u, // 奇子·树精
    SortOrder = 29)]
[SkipLocalsInit]
public sealed class XBMB29(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14618u);

// 第 39 组（斗兽奇弈高段 第二盘）：奇子·奇美拉
[SkipLocalsInit]
sealed class XBMB39States : RecordedCrucibleStates
{
    public XBMB39States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<CrucibleChimeraTether>()
            .ActivateOnEnter<CrucibleChimeraExpandingIce>()
            .ActivateOnEnter<XBMB39AOE>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB39States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14663,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14663u, // 奇子·奇美拉
    SortOrder = 39)]
[SkipLocalsInit]
public sealed class XBMB39(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14663u);

// 第 23 组（斗兽奇弈高段 第一盘）：奇子·魔界花 + 奇子·大口花[14601], 腐汁[14602], 奇子·幼苗[14600]
[SkipLocalsInit]
sealed class XBMB23States : RecordedCrucibleStates
{
    public XBMB23States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB23AOE>()
            .ActivateOnEnter<CrucibleMorbolAdds>()
            .ActivateOnEnter<CrucibleMorbolBreath>()
            .ActivateOnEnter<CrucibleMorbolPools>()
            .ActivateOnEnter<CrucibleMorbolKnockback>()
            .ActivateOnEnter<XBMB23Hint0>()
            .ActivateOnEnter<XBMB23Hint1>()
            .ActivateOnEnter<XBMB23Hint2>()
            .ActivateOnEnter<XBMB23Hint3>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB23States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14599,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14599u, // 奇子·魔界花
    SortOrder = 23)]
[SkipLocalsInit]
public sealed class XBMB23(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14599u);

// 第 45 组（斗兽奇弈高段 第二盘）：魔斧之主 劳妲 + 奇子·塔纳托斯[14699]
[SkipLocalsInit]
sealed class XBMB45States : RecordedCrucibleStates
{
    public XBMB45States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB45AOE>()
            .ActivateOnEnter<CrucibleLaudaBlades>()
            .ActivateOnEnter<CrucibleLaudaTorrent>()
            .ActivateOnEnter<CrucibleLaudaThunder>()
            .ActivateOnEnter<CrucibleLaudaBaits>()
            .ActivateOnEnter<CrucibleLaudaFireKnife>()
            .ActivateOnEnter<CrucibleLaudaShockwave>()
            .ActivateOnEnter<CrucibleLaudaLaterHint>()
            .ActivateOnEnter<CrucibleLaudaEmpoweredBlades>()
            .ActivateOnEnter<CrucibleLaudaAddRaidwide>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB45States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14693,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14693u, // 魔斧之主 劳妲
    SortOrder = 45)]
[SkipLocalsInit]
public sealed class XBMB45(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14693u);

// 第 25 组（斗兽奇弈高段 第一盘）：奇子·冰龙 + 冰元精[14607]
[SkipLocalsInit]
sealed class XBMB25States : RecordedCrucibleStates
{
    public XBMB25States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB25AOE>()
            .ActivateOnEnter<CrucibleIcePools>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB25States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14606,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14606u, // 奇子·冰龙
    SortOrder = 25)]
[SkipLocalsInit]
public sealed class XBMB25(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14606u);

// 第 28 组（斗兽奇弈高段 第一盘）：奇子·巨像
[SkipLocalsInit]
sealed class XBMB28States : RecordedCrucibleStates
{
    public XBMB28States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB28AOE>()
            .ActivateOnEnter<CrucibleGolemJump>()
            .ActivateOnEnter<CrucibleRockRain>()
            .ActivateOnEnter<CrucibleRockWalls>()
            .ActivateOnEnter<CrucibleGolemKnockback>()
            .ActivateOnEnter<CrucibleGolemKnockbackHint>()
            .ActivateOnEnter<CrucibleGolemSelfDestructHint>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB28States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14617,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14617u, // 奇子·巨像
    SortOrder = 28)]
[SkipLocalsInit]
public sealed class XBMB28(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14617u);

// 第 41 组（斗兽奇弈高段 第二盘）：奇子·巨人 + 奇子·独眼巨人[14671], 凝胶化火焰[14673], 凝胶化雷电[14672]
[SkipLocalsInit]
sealed class XBMB41States : RecordedCrucibleStates
{
    public XBMB41States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB41AOE>()
            .ActivateOnEnter<CrucibleGiantExplosionHint>()
            .ActivateOnEnter<CrucibleGiantSlimes>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB41States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14670,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14670u, // 奇子·巨人
    SortOrder = 41)]
[SkipLocalsInit]
public sealed class XBMB41(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14670u);

// 第 32 组（斗兽奇弈高段 第二盘）：奇子·佛劳洛斯 + 雷元精[14632]
[SkipLocalsInit]
sealed class XBMB32States : RecordedCrucibleStates
{
    public XBMB32States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB32AOE>()
            .ActivateOnEnter<XBMB32Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB32States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14631,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14631u, // 奇子·佛劳洛斯
    SortOrder = 32)]
[SkipLocalsInit]
public sealed class XBMB32(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14631u);

// 第 33 组（斗兽奇弈高段 第二盘）：奇子·夺心魔 + 奇子·毒性魔菇[14634]
[SkipLocalsInit]
sealed class XBMB33States : RecordedCrucibleStates
{
    public XBMB33States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB33AOE>()
            .ActivateOnEnter<CrucibleMindflayerAdds>()
            .ActivateOnEnter<CrucibleFungalBeds>()
            .ActivateOnEnter<CrucibleMindflayerWater>()
            .ActivateOnEnter<CrucibleMindflayerThunder>()
            .ActivateOnEnter<XBMB33Hint0>()
            .ActivateOnEnter<XBMB33Hint1>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB33States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14633,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14633u, // 奇子·夺心魔
    SortOrder = 33)]
[SkipLocalsInit]
public sealed class XBMB33(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14633u);

// 第 35 组（斗兽奇弈高段 第二盘）：奇子·阿托莫斯 + 奇子·红格雷姆林[14643], 奇子·奶冻怪[14646], 奇子·软糊怪[14645], 奇子·甜羹怪[14647], 奇子·石像魔[14648], 奇子·威胁扎哈克[14649]
[SkipLocalsInit]
sealed class XBMB35States : RecordedCrucibleStates
{
    public XBMB35States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB35AOE>()
            .ActivateOnEnter<CrucibleAtomosShockwave>()
            .ActivateOnEnter<CrucibleJellyWater>()
            .ActivateOnEnter<CrucibleJellyFire>()
            .ActivateOnEnter<CrucibleJellyThunder>()
            .ActivateOnEnter<XBMB35Hint0>()
            .ActivateOnEnter<XBMB35Hint1>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB35States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14642,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14642u, // 奇子·阿托莫斯
    SortOrder = 35)]
[SkipLocalsInit]
public sealed class XBMB35(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14642u);

// 第 38 组（斗兽奇弈高段 第二盘）：奇子·美杜莎 + 奇子·拉米亚[14661], 奇子·独眼巨人[14662]
[SkipLocalsInit]
sealed class XBMB38States : RecordedCrucibleStates
{
    public XBMB38States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB38AOE>()
            .ActivateOnEnter<CrucibleMedusaRay>()
            .ActivateOnEnter<XBMB38Hint0>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB38States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14660,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14660u, // 奇子·美杜莎
    SortOrder = 38)]
[SkipLocalsInit]
public sealed class XBMB38(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14660u);

// 第 42 组（斗兽奇弈高段 第二盘）：奇子·莫古小猛 + 奇子·莫古大医[14676], 奇子·莫古大术[14677], 奇子·莫古小贼[14683], 奇子·莫古大剑[14680], 奇子·莫古小术[14679], 奇子·莫古小医[14678], 奇子·莫古小歌[14681]
[SkipLocalsInit]
sealed class XBMB42States : StateMachineBuilder
{
    public XBMB42States(BossModule module) : base(module)
    {
        TrivialPhase()
            .ActivateOnEnter<XBMB42AOE>()
            .ActivateOnEnter<XBMB42Hint0>()
            .ActivateOnEnter<XBMB42Hint1>()
            .ActivateOnEnter<XBMB42Hint2>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB42States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14675,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14675u, // 奇子·莫古小猛
    SortOrder = 42)]
[SkipLocalsInit]
public sealed class XBMB42(WorldState ws, Actor primary) : CrucibleModule(ws, primary, 14675u);

// 第 40 组（斗兽奇弈高段 第二盘）：奇子·斯芬克斯
[SkipLocalsInit]
sealed class XBMB40States : RecordedCrucibleStates
{
    public XBMB40States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB40AOE>()
            .ActivateOnEnter<CrucibleSphinxRiddles>()
            .ActivateOnEnter<CrucibleSphinxNumbers>()
            .ActivateOnEnter<CrucibleSphinxRaidwide>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB40States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14665,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14665u, // 奇子·斯芬克斯
    SortOrder = 40)]
[SkipLocalsInit]
public sealed class XBMB40(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14665u);

// 第 43 组（斗兽奇弈高段 第二盘）：奇子·贝希摩斯 + 奇子·铁巨人[14685], 雷元精[14686]
[SkipLocalsInit]
sealed class XBMB43States : StateMachineBuilder
{
    public XBMB43States(BossModule module) : base(module)
    {
        TrivialPhase()
            .ActivateOnEnter<XBMB43AOE>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB43States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14684,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14684u, // 奇子·贝希摩斯
    SortOrder = 43)]
[SkipLocalsInit]
public sealed class XBMB43(WorldState ws, Actor primary) : CrucibleModule(ws, primary, 14684u);

// 第 44 组（斗兽奇弈高段 第二盘）：奇子·冥鬼之眼王 + 奇子·哈帕利特[14691], 奇子·肮脏之眼[14692]
[SkipLocalsInit]
sealed class XBMB44States : RecordedCrucibleStates
{
    public XBMB44States(BossModule module) : base(module)
    {
        GroupPhase()
            .ActivateOnEnter<XBMB44AOE>()
            .ActivateOnEnter<CrucibleEyeAttract>()
            .ActivateOnEnter<CrucibleEyeRoulette>()
            .ActivateOnEnter<CrucibleEyeGazes>()
            .ActivateOnEnter<CrucibleEyeBrands>()
            .ActivateOnEnter<CrucibleEyeRaidwide>()
            ;
    }
}

[ModuleInfo(BossModuleInfo.Maturity.Contributed,
    StatesType = typeof(XBMB44States),
    ObjectIDType = typeof(OID),
    ActionIDType = typeof(AID),
    StatusIDType = typeof(SID),
    PrimaryActorOID = (uint)OID.E14688,
    Contributors = "KanoNoUta",
    Expansion = BossModuleInfo.Expansion.Dawntrail,
    Category = BossModuleInfo.Category.Foray,
    GroupType = BossModuleInfo.GroupType.None,
    NameID = 14688u, // 奇子·冥鬼之眼王
    SortOrder = 44)]
[SkipLocalsInit]
public sealed class XBMB44(WorldState ws, Actor primary) : RecordedCrucibleModule(ws, primary, 14688u);
